# File: .readthedocs.yaml

version: 2

sphinx:
  configuration: doc/conf.py

python:
  # If you change this, you also need to update .github/workflows/test.yml
  # to make sure doc test builds run on the same version.
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

# Build PDF & ePub
formats:
  - epub
  - pdf
