language: python
python:
  - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils-gold libosmesa6-dev libegl1-mesa-dev

install:
  - pip install -r requirements.txt
  - pip install coveralls python-coveralls coverage

# command to run tests
script:
  - coverage run --source arcade setup.py test

deploy:
  provider: pypi
  user: $USERNAME
  password: $PASSWORD
  distributions: "bdist_rpm"

after_success:
  - coveralls