language: python
python:
  - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get update -qq

install:
  - pip install -r requirements.txt

script: echo

deploy:
  provider: pypi
  user: $USERNAME
  password: $PASSWORD
  distributions: "bdist_rpm"
