language: python

python:
  - "3.5"

# command to install dependencies
before_install:
  - sudo apt-get update -qq

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install -r requirements.txt

script: echo

deploy:
  provider: pypi
  user: $USERNAME
  password: $PASSWORD
  distributions: "bdist_rpm"
