name: test

on:
  push:
    branches: [development, maintenance, actions-test]
  pull_request:
    branches: [development, maintenance]
  workflow_dispatch:

jobs:

  build2:
    name: test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
        submodules: true

    - name: Install Mesa
      shell: cmd
      run: |
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" x mesa.7z
        mklink opengl32.dll "x64\opengl32.dll"
        mklink libglapi.dll "x64\libglapi.dll"

    - name: update-setuptools
      run: |
        python -m pip install -U pip wheel setuptools

    - name: install-arcade
      run: |
        python -m pip install -e .[dev]

    - name: Test with pytest
      run: |
        pytest