name: test

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  workflow_dispatch:

jobs:

  build:
    name: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10.0-rc.2']
        architecture: ['x64']

    steps:
      - uses: actions/checkout@v2      
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: deps
        run: |
          python -m pip install -U pip wheel setuptools mypy
      - name: build
        run: |
          python setup.py bdist_wheel
      - name: pytest
        run: mypy arcade
